name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - master
      - 'releases/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
          npm test
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.
      - run: |
          # Test upload
          echo "Hello, world!" | gh-actions-artifact-client.js upload test
          # Test download
          downloaded=$(gh-actions-artifact-client.js download test)
          echo $downloaded
          if [ "$downloaded" != "Hello, world!" ]; then
            echo "Downloaded content does not match uploaded content"
            exit 1
          fi
          # Test upload with different name
          echo "Another test" | gh-actions-artifact-client.js upload test2
          # Test download
          echo "Downloaded content: $(gh-actions-artifact-client.js download test2)"
          # Test delete
          gh-actions-artifact-client.js delete test2
          echo "Deleted test2"